package config

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

// starterTemplate is the single-profile config `axon setup` writes on a fresh
// install (the full two-profile tutorial lives in axon.config.example.yaml in
// the repo). Values chosen in the setup flow are baked in; everything else is
// a sensible personal-profile default the user can change with
// `axon configure` or by editing the file.
const starterTemplate = `# =============================================================================
# AXON configuration — generated by ` + "`axon setup`" + `.
# Single declarative source of AXON's behaviour. Secrets do NOT live here —
# they live in ~/.axon/.env (referenced as env:NAME). Change common settings
# with ` + "`axon configure`" + `, validate edits with ` + "`axon config validate`" + `.
# =============================================================================

version: 1
project_name: axon

active_profile: {{ .Profile }}

profiles:
  {{ .Profile }}:
    vault_path: "{{ .VaultPath }}"
    data_dir: "{{ .Home }}/profiles/{{ .Profile }}"

    claude:
      auth_mode: subscription                 # subscription | enterprise | api_key
      config_dir: "{{ .Home }}/profiles/{{ .Profile }}/claude"
      # Headless automations need a token from ` + "`claude setup-token`" + ` in ~/.axon/.env:
      oauth_token: env:CLAUDE_CODE_OAUTH_TOKEN

    dashboard:
      host: "127.0.0.1"
      port: 7777

    embeddings:
      provider: {{ .Provider }}               # ollama | apple (switch: axon configure embeddings <p> --reindex)
      host: "http://localhost:11434"          # ollama only
      model: {{ .Model }}
      dim: {{ .Dim }}
      batch_size: 32

    models:
      classify:  claude-haiku-4-5
      routine:   claude-sonnet-5
      synthesis: claude-opus-4-8
      eval_min_pass: 80                        # a local classify/routine tier must pass 'axon eval' at >= this %  (0 disables the gate)

    limits:
      daily_tokens:  1_500_000
      weekly_tokens: 8_000_000
      guard_pause_at_pct: 80

    retrieval:
      top_k: 8
      max_context_tokens: 12_000
      rerank: off                             # off | ollama:<model> — optional local reranker (best-effort, budget-exempt)

    ingestion:
      ocr: off                                # off | apple (macOS on-device Vision) | tesseract (pdftoppm+tesseract) — OCR fallback for scanned PDFs
      vision: off                             # off | ollama:<vision-model> (e.g. ollama:qwen2.5vl) | apple (macOS 27+) — local image description when OCR is sparse
      media_hosts: []                         # extra hosts auto-classified as caption-bearing media (YouTube family is built in)
      caption_langs: "en.*"                   # yt-dlp --sub-langs selector for media caption fetch

    research:
      enabled: false                          # deep-research automation; personal-first, off by default
      max_fetches: 8                          # per #deep question, hard cap on seed-URL fetches
      budget_tokens: 120_000                  # synthesis input budget (chokepoint-enforced)

    policy:
      data_residency: local-only
      egress_allowlist: ["localhost", "*"]
      ingest_domains_allow: ["*"]
      ingest_domains_deny: []
      redaction_rules: []
      allowed_automations: ["*"]

    automations:
      heartbeat:         { enabled: true,  schedule: "0 9,13,17 * * *", model: classify,  budget_tokens: 50_000,  catch_up: skip }
      daily-log:         { enabled: true,  schedule: "30 21 * * *",     model: routine,   budget_tokens: 120_000 }
      inbox-triage:      { enabled: true,  schedule: "*/30 * * * *",    model: routine,   budget_tokens: 80_000 }
      compaction:        { enabled: true,  schedule: "0 3 * * 0",       model: synthesis, budget_tokens: 300_000 }
      context-export:    { enabled: true,  schedule: "0 4 * * 0",       model: none,      budget_tokens: 0 }
      knowledge-reindex: { enabled: true,  schedule: "0 2 * * *",       model: none,      budget_tokens: 0 }
      knowledge-digest:  { enabled: true,  schedule: "0 8 * * 1",       model: synthesis, budget_tokens: 200_000 }
      research-questions: { enabled: false, schedule: "30 8 * * 1",      model: synthesis, budget_tokens: 150_000 }
      deep-research:     { enabled: false, schedule: "0 6 * * 1",       model: synthesis, budget_tokens: 120_000 }
      link-suggester:    { enabled: true,  schedule: "0 1 * * *",       model: classify,  budget_tokens: 60_000 }
      memory-distill:    { enabled: true,  schedule: "0 5 * * *",       model: synthesis, budget_tokens: 120_000 }
      budget-guard:      { enabled: true,  schedule: "*/15 * * * *",    model: none,      budget_tokens: 0 }
      capture:           { enabled: true,  schedule: "*/5 * * * *",     model: none,      budget_tokens: 0, catch_up: run-once }
      briefing:          { enabled: true,  schedule: "0 6 * * *",       model: routine,   budget_tokens: 40_000, catch_up: run-once }
      resurfacer:        { enabled: true,  schedule: "0 7 * * 1",       model: none,      budget_tokens: 0 }
      subscriptions:     { enabled: true,  schedule: "0 * * * *",       model: routine,   budget_tokens: 60_000, catch_up: skip }
      session-distill:   { enabled: true,  schedule: "15 */2 * * *",    model: classify,  budget_tokens: 30_000, catch_up: skip }
      entity-pages:      { enabled: false, schedule: "0 9 * * 1",       model: classify,  budget_tokens: 60_000 }
      project-pulse:     { enabled: false, schedule: "0 10 * * 1",      model: routine,   budget_tokens: 40_000 }
      merge-proposals:   { enabled: false, schedule: "0 11 * * 1",      model: none,      budget_tokens: 0 }
      actions-consolidate: { enabled: true, schedule: "0 7 * * *",      model: none,      budget_tokens: 0 }
      actions-review:      { enabled: false, schedule: "0 8 * * 6",      model: none,      budget_tokens: 0 }
      action-extract:      { enabled: false, schedule: "0 6 * * *",      model: routine,   budget_tokens: 60_000 }

    actions:
      stale_after_days: 30

    memory:
      inject: true
      session_tokens: 1500
      recent_entries: 10

    merge:
      threshold: 0.92
      max_proposals: 5
`

// Starter renders a fresh single-profile config for `axon setup`. provider is
// "ollama" or "apple"; model/dim follow it (Ollama defaults when empty).
// Data/config dirs are rooted at AXON_HOME when set — an isolated install must
// NEVER read or write the default ~/.axon profile data — and stay the portable
// literal "~/.axon" otherwise.
func Starter(profile, vaultPath, provider string) ([]byte, error) {
	model, dim := "nomic-embed-text", 768
	if provider == "apple" {
		model, dim = AppleEmbeddingModel, AppleEmbeddingDim
	}
	home := DefaultAxonHome // portable "~/.axon" in the common case
	if v := os.Getenv("AXON_HOME"); v != "" {
		home = ExpandPath(v)
	}
	tpl, err := template.New("starter").Parse(starterTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, map[string]any{
		"Profile": profile, "VaultPath": vaultPath, "Provider": provider, "Model": model, "Dim": dim, "Home": home,
	}); err != nil {
		return nil, err
	}
	// A starter that doesn't validate is a bug, not a user error.
	if _, err := Parse(buf.Bytes()); err != nil {
		return nil, fmt.Errorf("generated starter config is invalid (bug): %w", err)
	}
	return buf.Bytes(), nil
}
