package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// onboardAnswers is a small YAML answers file for unattended onboarding.
const onboardAnswers = `name: Jandro
role: Engineer
timezone: Europe/Madrid
communication: concise, bullets
goals: [ship AXON]
people: [Ada]
projects: [AXON]
agent_name: Axon
tone: direct
boundaries: [ask before sending anything outward]
`

func TestOnboardCreatesLayerAndIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	cfgPath := writeTempConfig(t, dir)
	env := filepath.Join(dir, "nonexistent.env")
	answers := filepath.Join(dir, "answers.yaml")
	if err := os.WriteFile(answers, []byte(onboardAnswers), 0o644); err != nil {
		t.Fatal(err)
	}

	out, err := run(t, "onboard", "--config", cfgPath, "--env", env, "--non-interactive", "--from", answers)
	if err != nil {
		t.Fatalf("onboard failed: %v\n%s", err, out)
	}
	if !strings.Contains(out, "created") {
		t.Errorf("onboard summary missing created files:\n%s", out)
	}
	profileDir := filepath.Join(dir, "vault", "02-Areas", "Profile")
	for _, f := range []string{"USER.md", "SOUL.md", "MEMORY.md"} {
		if _, err := os.Stat(filepath.Join(profileDir, f)); err != nil {
			t.Errorf("onboard did not create %s: %v", f, err)
		}
	}
	// Interviewed values land in USER.md.
	userMD, _ := os.ReadFile(filepath.Join(profileDir, "USER.md"))
	if !strings.Contains(string(userMD), "Jandro") || !strings.Contains(string(userMD), "[[AXON]]") {
		t.Errorf("USER.md missing interviewed values:\n%s", userMD)
	}
	// Claude Code wiring is (re)generated by onboarding too.
	if _, err := os.Stat(filepath.Join(dir, "vault", ".claude", ".mcp.json")); err != nil {
		t.Errorf("onboard did not ensure Claude Code wiring: %v", err)
	}

	// Second run converges and never clobbers.
	out2, err := run(t, "onboard", "--config", cfgPath, "--env", env, "--non-interactive", "--from", answers)
	if err != nil {
		t.Fatalf("second onboard failed: %v\n%s", err, out2)
	}
	if !strings.Contains(out2, "kept") {
		t.Errorf("second onboard should keep existing files:\n%s", out2)
	}
}

func TestOnboardJSONIsSecretFree(t *testing.T) {
	dir := t.TempDir()
	cfgPath := writeTempConfig(t, dir)
	env := filepath.Join(dir, "nonexistent.env")
	answers := filepath.Join(dir, "answers.yaml")
	if err := os.WriteFile(answers, []byte(onboardAnswers), 0o644); err != nil {
		t.Fatal(err)
	}
	out, err := run(t, "onboard", "--config", cfgPath, "--env", env, "--json", "--from", answers)
	if err != nil {
		t.Fatalf("onboard --json failed: %v\n%s", err, out)
	}
	var rep struct {
		Profile string   `json:"profile"`
		Mode    string   `json:"mode"`
		Created []string `json:"created"`
		OK      bool     `json:"ok"`
	}
	// The JSON is the last document on stdout.
	dec := json.NewDecoder(strings.NewReader(out))
	if err := dec.Decode(&rep); err != nil {
		t.Fatalf("onboard --json did not emit valid JSON: %v\n%s", err, out)
	}
	if !rep.OK || rep.Profile != "personal" || rep.Mode != "first-run" || len(rep.Created) == 0 {
		t.Errorf("unexpected onboard report: %+v", rep)
	}
}
